package com.ch4k4uw.domain.moviecatalog.abstraction.repository.specification

import com.ch4k4uw.domain.abstraction.repository.specification.LongIdRepositorySpecification
import com.ch4k4uw.domain.common.abstraction.entity.MovieTypeEntity

interface MovieTypeQueryRepositoryListSpecitication: LongIdRepositorySpecification<MovieTypeEntity>